defaults:
  - requires_package: &requires_package
      requires:
        - build-package

workflows:
  version: 2.1
  pr-checks:
    jobs:
      - check-coding-style
      - node-v10
      - node-v12
      - node-v14
      - node-v16
      - node-v18
      - node-v20
      - node-current:
          run_coveralls: true
      - build-package
      - hardhat-sample-project: *requires_package
      - cli-smoke-test: *requires_package
      - hyperion-hypcjs-ext-test

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main

    jobs:
      - node-current
      - build-package
      - hardhat-sample-project: *requires_package
      - cli-smoke-test: *requires_package
      - hyperion-hypcjs-ext-test

version: 2.1

orbs:
  shellcheck: circleci/shellcheck@volatile

commands:
  show-npm-version:
    steps:
      - run:
          name: Versions
          command: |
            npm version
            yarn --version
            pnpm version || >&2 echo "pnpm not installed"

  install-dependencies:
    parameters:
      cache-id:
        type: string
      path:
        type: string
        default: .
      package-manager:
        type: string
        default: npm
      dependency-file:
        type: string
        default: package.json
    steps:
      - restore_cache:
          name: "Restoring <<parameters.cache-id>> cache"
          key: <<parameters.cache-id>>-dependency-cache-v5-{{ .Environment.CIRCLE_JOB }}-{{ checksum "<<parameters.path>>/<<parameters.dependency-file>>" }}
      - run:
          name: "<<parameters.package-manager>> install in <<parameters.path>>"
          command: |
            cd "<<parameters.path>>"
            if [[ ! -e node_modules/ ]]; then
              if [[ "<<parameters.package-manager>>" == "pnpm" ]]; then
                # Create a flat node_modules without symlinks. Same as the node_modules created by npm or Yarn.
                <<parameters.package-manager>> install --no-frozen-lockfile --node-linker=hoisted
              else
                <<parameters.package-manager>> install
              fi
            fi
      - save_cache:
          name: "Saving <<parameters.cache-id>> cache"
          key: <<parameters.cache-id>>-dependency-cache-v5-{{ .Environment.CIRCLE_JOB }}-{{ checksum "<<parameters.path>>/<<parameters.dependency-file>>" }}
          paths:
            - "<<parameters.path>>/node_modules/"

  inject-hypc-js-tarball:
    description: "Recursively finds and replaces all instances of hypc-js module installed in node_modules/ with the one from a tarball."
    parameters:
      path:
        type: string
        default: .
      tarball-path:
        type: string
        default: workspace/hypc-js.tgz
      package-manager:
        type: enum
        enum: ["npm", "yarn", "pnpm"]
        default: npm
    steps:
      - run:
          name: "Sanity check: tarball exists and the target dir contains a JS project"
          command: |
            [[ -f "<<parameters.tarball-path>>" ]]
            [[ -f "<<parameters.path>>/package.json" ]]
      - run:
          name: Inject hypc-js from the tarball into dependencies at <<parameters.path>>
          command: |
            absolute_tarball_path=$(realpath "<<parameters.tarball-path>>")
            cd "<<parameters.path>>"
            mv package.json original-package.json
            # NOTE: The 'overrides' feature requires npm >= 8.3. Yarn requires `resolutions` instead.
            jq ". + {overrides: {hypc: \"${absolute_tarball_path}\"}} + {resolutions: {hypc: \"${absolute_tarball_path}\"}}" original-package.json > package.json
            if [[ "<<parameters.package-manager>>" == "pnpm" ]]; then
              <<parameters.package-manager>> install --no-frozen-lockfile --node-linker=hoisted
            else
              <<parameters.package-manager>> install
            fi
      - run:
          name: "Sanity check: all transitive dependencies successfully replaced with the tarball"
          command: |
            hypc_version=$(
              tar --extract --to-stdout --file "<<parameters.tarball-path>>" package/package.json |
              jq --raw-output .version
            )
            cd "<<parameters.path>>"
            if [[ "<<parameters.package-manager>>" == "pnpm" ]]; then
              dependency_version=$(pnpm list --depth Infinity hypc | grep "hypc" | grep -v "hypc ${hypc_version}" || true)
            else
              dependency_version=$(<<parameters.package-manager>> list hypc | grep "hypc@" | grep -v "hypc@${hypc_version}" || true)
            fi
            if [[ -n "${dependency_version}" ]]; then
              echo "Another version of hypc-js is still present in the dependency tree."
              exit 1
            fi

  fetch-latest-hardhat-release-tag:
    description: "Uses GitHub API to fetch the latest hardhat release version."
    steps:
      - run:
          name: Retrieve Hardhat latest release tag
          command: |
            # Make authenticated requests when the Github token is available
            if [[ -n "$GITHUB_ACCESS_TOKEN" ]]; then
              EXTRA_HEADERS=(--header "Authorization: Bearer ${GITHUB_ACCESS_TOKEN}")
            fi
            HARDHAT_LATEST_RELEASE_TAG=$(
              curl \
                --silent \
                --location \
                --fail \
                --show-error \
                "${EXTRA_HEADERS[@]}" \
                https://api.github.com/repos/nomiclabs/hardhat/releases \
                | jq --raw-output 'map(select(.tag_name | test("^hardhat@"))) | .[0].tag_name' \
            )
            echo "export HARDHAT_LATEST_RELEASE_TAG='${HARDHAT_LATEST_RELEASE_TAG}'" >> "$BASH_ENV"

jobs:
  node-base: &node-base
    working_directory: ~/hypc-js
    docker:
      - image: cimg/node:current
    parameters:
      run_coveralls:
        type: boolean
        default: false
    steps:
      # We want the default npm here. Older one might not work with older node.js
      - show-npm-version
      - checkout
      - install-dependencies:
          cache-id: hypc-js
      - run:
          name: updateBinary
          command: npm run updateBinary
      - run:
          name: test
          command: npm run test
      - when:
          condition: <<parameters.run_coveralls>>
          steps:
            - run:
                name: coveralls
                command: npm run coveralls

  check-coding-style:
    docker:
      - image: cimg/node:current
    steps:
      - show-npm-version
      - checkout
      - shellcheck/install
      - install-dependencies:
          cache-id: hypc-js
      - run:
          name: Check for javascript/typescript coding style
          command: npm run lint
      - shellcheck/check:
          ignore-dirs: |
            ./.git
            ./node_modules
            ./dist

  build-package:
    docker:
      - image: cimg/node:current
    steps:
      - show-npm-version
      - checkout:
          path: hypc-js/
      - install-dependencies:
          cache-id: hypc-js
          path: hypc-js
      - attach_workspace:
          at: workspace
      - run:
          name: Package hypc-js
          command: |
            cd hypc-js/
            npm run build:tarball

            cp "$(npm run --silent tarballName)" ../workspace/hypc-js.tgz

            # The artifact is meant to be used with `npm publish` and that fails unless the file name includes a version number.
            # Oddly, the name and version from the file name do not even need to be correct - after npm accepts the file,
            # it will use the ones from package.json anyway.
            mkdir ../artifacts
            mv "$(npm run --silent tarballName)" ../artifacts/
      - persist_to_workspace:
          root: workspace
          paths:
            - hypc-js.tgz
      - store_artifacts:
          path: artifacts/

  hardhat-sample-project:
    docker:
      - image: cimg/node:current
    steps:
      - show-npm-version
      - attach_workspace:
          at: workspace
      - run: git clone --depth 1 "https://github.com/nomiclabs/hardhat-hackathon-boilerplate" boilerplate/
      - run:
          # Leaving package-lock.json causes a weird error in arborist when npm is used again after
          # `npm install`: 'The "from" argument must be of type string. Received undefined'
          name: Neutralize package-lock.json
          command: rm boilerplate/package-lock.json
      - install-dependencies:
          cache-id: hardhat-hackathon-boilerplate
          path: boilerplate
      - fetch-latest-hardhat-release-tag
      - run:
          name: Update to the latest Hardhat release
          command: |
            # We can just use a release here because injection does not require rebuilding it.
            cd boilerplate/
            # Install the latest release of Hardhat if the version matches the expected format.
            [[ "${HARDHAT_LATEST_RELEASE_TAG}" =~ ^hardhat@([0-9]+\.){2}[0-9]+$ ]] && npm install ${HARDHAT_LATEST_RELEASE_TAG}

      - inject-hypc-js-tarball:
          path: boilerplate/
      - run:
          name: Configure the boilerplate project to force Hardhat not to use a native binary
          command: |
            cd boilerplate/

            hypc_version=$(jq --raw-output .version node_modules/hypc/package.json)

            sed -i 's|pragma hyperion [^;]\+;|pragma hyperion *;|g' contracts/Token.sol

            {
              echo "const {TASK_COMPILE_HYPERION_GET_HYPC_BUILD} = require('hardhat/builtin-tasks/task-names');"
              echo "const assert = require('assert');"
              echo
              echo "subtask(TASK_COMPILE_HYPERION_GET_HYPC_BUILD, async (args, hre, runSuper) => {"
              echo "    assert(args.hypcVersion == '${hypc_version}', 'Unexpected hypc version: ' + args.hypcVersion);"
              echo "    return {"
              echo "        compilerPath: '$(realpath "node_modules/hypc/hypjson.js")',"
              echo "        isHypcJs: true,"
              echo "        version: args.hypcVersion,"
              echo "        longVersion: args.hypcVersion"
              echo "    };"
              echo "})"
              echo "module.exports = {hyperion: '${hypc_version}'};"
            } >> hardhat.config.js
      - run:
          name: Build and test the boilerplate project with local Hardhat
          command: |
            cd boilerplate/
            npm run test

  cli-smoke-test:
    docker:
      - image: cimg/node:current
    steps:
      - show-npm-version
      - attach_workspace:
          at: workspace
      - run:
          name: "CLI smoke test (package)"
          command: |
            mkdir package/
            cd package/
            npm install ../workspace/hypc-js.tgz

            npx hypcjs --version

            echo "contract C {}" > C.hyp
            npx hypcjs C.sol --bin
            [[ -f C_sol_C.bin ]]
      - checkout:
          path: hypc-js/
      - install-dependencies:
          cache-id: hypc-js
          path: hypc-js
      - run:
          name: Build hypc-js
          command: |
            cd hypc-js/
            npm run updateBinary
            npm run build
      - run:
          name: "CLI smoke test (repository)"
          command: |
            cd hypc-js
            dist/hypc.js --version

            echo "contract C {}" > C.sol
            dist/hypc.js C.sol --bin
            [[ -f C_sol_C.bin ]]

  hyperion-hypcjs-ext-test:
    docker:
      - image: cimg/node:current
    steps:
      - show-npm-version
      - checkout:
          path: hypc-js/
      - run: git clone --depth 1 "https://github.com/theQRL/hyperion" hyperion/
      - run: cd hyperion/ && curl "https://binaries.soliditylang.org/bin/soljson-nightly.js" --location --output hypjson.js
      - run: cd hyperion/ && test/externalTests/hypc-js/hypc-js.sh "$(realpath hypjson.js)" "$(scripts/get_version.sh)" "$(realpath ../hypc-js/)"

  node-v10:
    <<: *node-base
    docker:
      - image: cimg/node:10.24
  node-v12:
    <<: *node-base
    docker:
      - image: cimg/node:12.22
  node-v14:
    <<: *node-base
    docker:
      - image: cimg/node:14.21
  node-v16:
    <<: *node-base
    docker:
      - image: cimg/node:16.20
  node-v18:
    <<: *node-base
    docker:
      - image: cimg/node:18.18
  node-v20:
    <<: *node-base
    docker:
      - image: cimg/node:20.9
  node-current:
    <<: *node-base
    docker:
      - image: cimg/node:current
